# Generated by Django 5.2.10 on 2026-01-22 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название направления подготовки')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Шифр УГСН')),
                ('study_form', models.CharField(max_length=30, verbose_name='Форма обучения')),
                ('admission_plan', models.PositiveIntegerField(default=0, verbose_name='План приема')),
                ('target_avg_score', models.FloatField(default=0.0, verbose_name='Целевой средний балл')),
                ('status', models.CharField(default='Активно', max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Направления подготовки',
                'verbose_name_plural': 'Направления подготовки',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название предмета')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код предмета')),
            ],
            options={
                'verbose_name': 'Предмет ЕГЭ',
                'verbose_name_plural': 'Предметы ЕГЭ',
            },
        ),
        migrations.CreateModel(
            name='ProgramSubjectRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.PositiveIntegerField(verbose_name='Минимальный балл')),
                ('year', models.PositiveIntegerField(verbose_name='Год действия')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.educationprograms', verbose_name='Направление')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subjects', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Требования по предмету',
                'verbose_name_plural': 'Требования по предметам',
                'unique_together': {('program_id', 'subject_id', 'year')},
            },
        ),
        migrations.AddField(
            model_name='educationprograms',
            name='subjects',
            field=models.ManyToManyField(through='api.ProgramSubjectRequirements', to='api.subjects', verbose_name='Требования по предметам'),
        ),
    ]
