# Generated by Django 5.2.10 on 2026-02-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_programsubjectrequirements_is_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprograms',
            name='school',
            field=models.CharField(choices=[('1', 'ИМКТ'), ('2', 'ШЭМ'), ('3', 'ШМиНЖ'), ('4', 'ИТПМ'), ('5', 'ИФКС'), ('6', 'ЮШ'), ('7', 'ШИГН'), ('8', 'ПИШ'), ('9', 'ШП'), ('10', 'ВИ'), ('11', 'ИМО'), ('12', 'ПИ')], default=1, verbose_name='Институт'),
            preserve_default=False,
        ),
    ]
