# Generated by Django 5.2.10 on 2026-01-25 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationprograms',
            name='code',
            field=models.CharField(help_text='Формат: xx.xx.xx (например, 09.03.04)', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Шифр УГСН должен быть в формате xx.xx.xx (например, 09.03.04).', regex='^\\d{2}\\.\\d{2}\\.\\d{2}$')], verbose_name='Шифр УГСН'),
        ),
        migrations.AlterField(
            model_name='educationprograms',
            name='study_form',
            field=models.CharField(choices=[('очная', 'Очное'), ('очно-заочная', 'Очно-заочное'), ('заочная', 'Заочное')], max_length=30, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='programsubjectrequirements',
            name='year',
            field=models.PositiveIntegerField(choices=[(2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031')], verbose_name='Год действия'),
        ),
    ]
