# Generated by Django 5.2.10 on 2026-01-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_educationprograms_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsubjectrequirements',
            name='is_optional',
            field=models.BooleanField(default=False, help_text="Если включено — предмет не обязательный, учитывается как 'по выбору'.", verbose_name='Предмет по выбору'),
        ),
    ]
