# Generated by Django 5.2.10 on 2026-05-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_educationprograms_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Идет обновление'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='running', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(verbose_name='Начало обновления')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание обновления')),
                ('total_loaded', models.PositiveIntegerField(default=0, verbose_name='Загружено записей')),
                ('error_message', models.TextField(blank=True, verbose_name='Текст ошибки')),
            ],
            options={
                'verbose_name': 'Импорт данных',
                'verbose_name_plural': 'Импорты данных',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_interval_minutes', models.PositiveIntegerField(default=30, verbose_name='Интервал обновления в минутах')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Автоматическое обновление включено')),
            ],
            options={
                'verbose_name': 'Настройки импорта',
                'verbose_name_plural': 'Настройки импорта',
            },
        ),
        migrations.CreateModel(
            name='ApplicantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=64, verbose_name='ID студента')),
                ('student_name', models.CharField(max_length=255, verbose_name='ФИО студента')),
                ('direction_code', models.CharField(db_index=True, max_length=32, verbose_name='Код направления')),
                ('direction_name', models.CharField(max_length=255, verbose_name='Направление')),
                ('avg_score', models.FloatField(verbose_name='Средний балл')),
                ('approval', models.BooleanField(default=False, verbose_name='Подано согласие')),
                ('high_priority_no_original', models.BooleanField(default=False, verbose_name='ВПР без оригинала')),
                ('top_priority', models.BooleanField(default=False, verbose_name='Высший приоритет')),
                ('status_vuz', models.CharField(blank=True, max_length=255, verbose_name='Статус ВУЗ')),
                ('category', models.CharField(blank=True, max_length=255, verbose_name='Категория')),
                ('level_education', models.CharField(blank=True, max_length=255, verbose_name='Уровень образования')),
                ('actual', models.BooleanField(default=True, verbose_name='Актуальная запись')),
                ('imported_at', models.DateTimeField(auto_now=True, verbose_name='Дата импорта')),
            ],
            options={
                'verbose_name': 'Заявление абитуриента',
                'verbose_name_plural': 'Заявления абитуриентов',
                'indexes': [models.Index(fields=['direction_code'], name='api_applica_directi_9bb00d_idx'), models.Index(fields=['actual'], name='api_applica_actual_193690_idx'), models.Index(fields=['top_priority'], name='api_applica_top_pri_fb3cc5_idx')],
            },
        ),
    ]
