# Generated by Django 5.2.10 on 2026-05-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dataimport_importsettings_applicantapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantapplication',
            name='no_exams',
            field=models.BooleanField(default=False, verbose_name='БВИ / без экзаменов'),
        ),
        migrations.AddField(
            model_name='applicantapplication',
            name='sum_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма баллов'),
        ),
        migrations.AlterField(
            model_name='educationprograms',
            name='school',
            field=models.CharField(choices=[('1', 'ИМКТ'), ('2', 'ШЭМ'), ('3', 'ШМиНЖ'), ('4', 'ИТПМ'), ('5', 'ИФКС'), ('6', 'ЮШ'), ('7', 'ШИГН'), ('8', 'ПИШ'), ('9', 'ШП'), ('10', 'ВИ'), ('11', 'ИМО'), ('12', 'ПИ')], max_length=10, verbose_name='Институт'),
        ),
    ]
