# Generated by Django 5.2.10 on 2026-07-07 14:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('1', 'ИМКТ'), ('2', 'ШЭМ'), ('3', 'ШМиНЖ'), ('4', 'ИТПМ'), ('5', 'ИФКС'), ('6', 'ЮШ'), ('7', 'ШИГН'), ('8', 'ПИШ'), ('9', 'ШП'), ('10', 'ВИ'), ('11', 'ИМО'), ('12', 'ПИ')], max_length=10, verbose_name='Институт')),
                ('name', models.CharField(max_length=255, verbose_name='Название направления подготовки')),
                ('code', models.CharField(db_index=True, help_text='Формат: xx.xx.xx, например 09.03.04.', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Шифр УГСН должен быть в формате xx.xx.xx, например 09.03.04.', regex='^\\d{2}\\.\\d{2}\\.\\d{2}$')], verbose_name='Шифр направления')),
                ('education_level', models.CharField(choices=[('bachelor_specialist', 'Бакалавриат/Специалитет'), ('bachelor', 'Бакалавриат'), ('specialist', 'Специалитет'), ('bvo', 'БВО')], default='bachelor_specialist', max_length=50, verbose_name='Уровень образования')),
                ('study_form', models.CharField(choices=[('очная', 'Очная'), ('очно-заочная', 'Очно-заочная'), ('заочная', 'Заочная')], default='очная', max_length=30, verbose_name='Форма обучения')),
                ('admission_plan', models.PositiveIntegerField(default=0, verbose_name='План приема')),
                ('target_avg_score', models.FloatField(default=0.0, verbose_name='Целевой средний балл')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('archived', 'Архив'), ('hidden', 'Скрыто')], db_index=True, default='active', max_length=30, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Образовательная программа',
                'verbose_name_plural': 'Образовательные программы',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название предмета')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSubjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.PositiveIntegerField(verbose_name='Минимальный балл')),
                ('year', models.PositiveIntegerField(choices=[(2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031')], verbose_name='Год действия')),
                ('is_optional', models.BooleanField(default=False, help_text='Если включено, предмет учитывается как предмет по выбору.', verbose_name='Предмет по выбору')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_requirements', to='programs.educationprogram', verbose_name='Направление')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_requirements', to='programs.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Требование по предмету',
                'verbose_name_plural': 'Требования по предметам',
                'ordering': ['program__code', 'subject__name'],
            },
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='subjects',
            field=models.ManyToManyField(through='programs.ProgramSubjectRequirement', to='programs.subject', verbose_name='Требования по предметам'),
        ),
        migrations.AddConstraint(
            model_name='programsubjectrequirement',
            constraint=models.UniqueConstraint(fields=('program', 'subject', 'year'), name='unique_program_subject_requirement_by_year'),
        ),
        migrations.AddIndex(
            model_name='educationprogram',
            index=models.Index(fields=['code'], name='programs_ed_code_d0afc0_idx'),
        ),
        migrations.AddIndex(
            model_name='educationprogram',
            index=models.Index(fields=['status'], name='programs_ed_status_62855f_idx'),
        ),
        migrations.AddIndex(
            model_name='educationprogram',
            index=models.Index(fields=['school'], name='programs_ed_school_6b2a90_idx'),
        ),
        migrations.AddIndex(
            model_name='educationprogram',
            index=models.Index(fields=['education_level'], name='programs_ed_educati_99ceae_idx'),
        ),
        migrations.AddIndex(
            model_name='educationprogram',
            index=models.Index(fields=['study_form'], name='programs_ed_study_f_aab30e_idx'),
        ),
    ]
