# Generated by Django 5.2.10 on 2026-07-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='is_op_admission',
            field=models.BooleanField(default=False, help_text='Если включено, заявления по этому коду не будут схлопываться только по коду направления. Уникальность будет считаться по связке: абитуриент + код + название ОП.', verbose_name='Приём на ОП'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='is_priority_2030',
            field=models.BooleanField(default=False, help_text='Если включено, направление попадёт в отдельную статистику по приоритетным направлениям.', verbose_name='Приоритет 2030'),
        ),
        migrations.CreateModel(
            name='PriorityTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('priority_total', 'Приоритет 2030 в целом'), ('priority_ugsn', 'УГСН в Приоритете 2030')], max_length=50, verbose_name='Тип целевого показателя')),
                ('ugsn_code', models.CharField(blank=True, default='', help_text='Например: 45.00.00. Для общего показателя Приоритета 2030 оставить пустым.', max_length=20, verbose_name='Код УГСН')),
                ('ugsn_name', models.CharField(blank=True, default='', max_length=500, verbose_name='Название УГСН')),
                ('target_avg_score', models.FloatField(default=0, verbose_name='Целевой средний балл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Целевой показатель Приоритета 2030',
                'verbose_name_plural': 'Целевые показатели Приоритета 2030',
                'ordering': ['target_type', 'ugsn_code'],
                'constraints': [models.UniqueConstraint(fields=('target_type', 'ugsn_code'), name='unique_priority_target_by_type_and_ugsn')],
            },
        ),
    ]
