# Generated by Django 5.2.10 on 2026-07-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_educationprogram_is_op_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='is_new_model',
            field=models.BooleanField(default=False, help_text='Если включено, направление попадёт в отдельную статистику по новой модели.', verbose_name='Новая модель'),
        ),
    ]
