# Generated by Django 5.2.10 on 2026-07-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=64, verbose_name='ID абитуриента')),
                ('student_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО абитуриента')),
                ('direction_code', models.CharField(db_index=True, max_length=32, verbose_name='Код направления')),
                ('direction_name', models.CharField(blank=True, max_length=255, verbose_name='Направление')),
                ('avg_score', models.FloatField(verbose_name='Средний балл')),
                ('sum_score', models.PositiveIntegerField(default=0, verbose_name='Сумма баллов')),
                ('no_exams', models.BooleanField(db_index=True, default=False, verbose_name='БВИ / без экзаменов')),
                ('approval', models.BooleanField(db_index=True, default=False, verbose_name='Подано согласие')),
                ('high_priority_no_original', models.BooleanField(default=False, verbose_name='Высший приоритет без оригинала')),
                ('top_priority', models.BooleanField(db_index=True, default=False, verbose_name='Высший приоритет')),
                ('status_vuz', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Статус заявления')),
                ('category', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Категория конкурса')),
                ('level_education', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Уровень образования')),
                ('actual', models.BooleanField(db_index=True, default=True, verbose_name='Актуальная запись')),
                ('imported_at', models.DateTimeField(auto_now=True, verbose_name='Дата импорта')),
            ],
            options={
                'verbose_name': 'Заявление абитуриента',
                'verbose_name_plural': 'Заявления абитуриентов',
                'ordering': ['direction_code', '-avg_score', '-sum_score', 'student_name'],
                'indexes': [models.Index(fields=['direction_code'], name='admissions__directi_dc433d_idx'), models.Index(fields=['student_id'], name='admissions__student_8a1ce5_idx'), models.Index(fields=['direction_code', '-avg_score'], name='admissions__directi_348c30_idx'), models.Index(fields=['direction_code', 'approval'], name='admissions__directi_1344e7_idx'), models.Index(fields=['direction_code', 'top_priority'], name='admissions__directi_a7675b_idx'), models.Index(fields=['category'], name='admissions__categor_aa105a_idx'), models.Index(fields=['level_education'], name='admissions__level_e_c07539_idx'), models.Index(fields=['actual'], name='admissions__actual_1a6661_idx')],
                'constraints': [models.UniqueConstraint(fields=('student_id', 'direction_code'), name='unique_applicant_application_by_direction')],
            },
        ),
    ]
