# Generated by Django 5.2.10 on 2026-07-08 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('imports', '0002_alter_importsettings_is_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VppAverageScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('university', 'Университет'), ('direction', 'Направление')], max_length=20, verbose_name='Область расчёта')),
                ('direction_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Код направления')),
                ('direction_name', models.CharField(blank=True, default='', max_length=500, verbose_name='Название направления')),
                ('average_score_by_plan', models.FloatField(blank=True, null=True, verbose_name='Средний по плану')),
                ('average_score_by_vpp_count', models.FloatField(blank=True, null=True, verbose_name='Средний по ВПП')),
                ('plan_score_sum', models.FloatField(default=0.0, verbose_name='Сумма средних баллов ВПП')),
                ('admission_plan', models.PositiveIntegerField(default=0, verbose_name='План набора')),
                ('plan_applications_count', models.PositiveIntegerField(default=0, verbose_name='ВПП в плане')),
                ('plan_missing_count', models.PositiveIntegerField(default=0, verbose_name='Не хватает ВПП')),
                ('plan_fill_percent', models.FloatField(default=0.0, verbose_name='Заполнение плана, %')),
                ('total_applications', models.PositiveIntegerField(default=0, verbose_name='Всего заявлений')),
                ('approvals_count', models.PositiveIntegerField(default=0, verbose_name='Согласий')),
                ('top_priority_count', models.PositiveIntegerField(default=0, verbose_name='ВПП всего')),
                ('imported_at', models.DateTimeField(verbose_name='Дата импорта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания снимка')),
                ('import_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpp_average_score_snapshots', to='imports.dataimport', verbose_name='Импорт')),
            ],
            options={
                'verbose_name': 'Снимок среднего балла по ВПП',
                'verbose_name_plural': 'Снимки среднего балла по ВПП',
                'ordering': ['-imported_at', 'scope', 'direction_code'],
                'constraints': [models.UniqueConstraint(fields=('import_log', 'scope', 'direction_code'), name='unique_vpp_average_snapshot_per_import_scope_direction')],
            },
        ),
    ]
