# Generated by Django 5.2.10 on 2026-07-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_vppaveragescoresnapshot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicantapplication',
            name='unique_applicant_application_by_direction',
        ),
        migrations.AddConstraint(
            model_name='applicantapplication',
            constraint=models.UniqueConstraint(fields=('student_id', 'direction_code', 'direction_name'), name='unique_applicant_application_by_direction'),
        ),
    ]
