# Generated by Django 5.2.10 on 2026-07-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('local_json', 'Локальный JSON'), ('soap', 'SOAP-сервис')], default='local_json', max_length=20, verbose_name='Источник данных')),
                ('service_url', models.URLField(blank=True, verbose_name='Адрес SOAP-сервиса')),
                ('soap_action', models.CharField(blank=True, max_length=255, verbose_name='SOAPAction')),
                ('service_login', models.CharField(blank=True, max_length=255, verbose_name='Логин SOAP-сервиса')),
                ('service_password', models.CharField(blank=True, max_length=255, verbose_name='Пароль SOAP-сервиса')),
                ('soap_timeout_seconds', models.PositiveIntegerField(default=60, verbose_name='Таймаут SOAP-запроса, секунд')),
                ('verify_ssl', models.BooleanField(default=True, verbose_name='Проверять SSL-сертификат')),
                ('update_interval_minutes', models.PositiveIntegerField(choices=[(30, 'Раз в 30 минут'), (60, 'Раз в 1 час'), (180, 'Раз в 3 часа'), (1440, 'Раз в сутки')], default=30, verbose_name='Интервал обновления')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Автоматическое обновление включено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения настроек')),
            ],
            options={
                'verbose_name': 'Настройки импорта',
                'verbose_name_plural': 'Настройки импорта',
            },
        ),
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Идет обновление'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], default='pending', max_length=20, verbose_name='Статус')),
                ('trigger', models.CharField(choices=[('manual', 'Ручной запуск'), ('scheduled', 'Автоматический запуск')], default='manual', max_length=20, verbose_name='Тип запуска')),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Плановое время запуска')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ID Celery-задачи')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало обновления')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание обновления')),
                ('total_received', models.PositiveIntegerField(default=0, verbose_name='Получено записей из источника')),
                ('total_loaded', models.PositiveIntegerField(default=0, verbose_name='Загружено подходящих записей')),
                ('error_message', models.TextField(blank=True, verbose_name='Текст ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Импорт данных',
                'verbose_name_plural': 'Импорты данных',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='imports_dat_status_86d7dc_idx'), models.Index(fields=['trigger'], name='imports_dat_trigger_79a7d6_idx'), models.Index(fields=['scheduled_for'], name='imports_dat_schedul_774c0c_idx'), models.Index(fields=['celery_task_id'], name='imports_dat_celery__b325aa_idx')],
                'constraints': [models.UniqueConstraint(fields=('trigger', 'scheduled_for'), name='unique_scheduled_import_slot')],
            },
        ),
    ]
