# Generated by Django 5.2.10 on 2026-07-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsettings',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='Автоматическое обновление включено'),
        ),
        migrations.AlterField(
            model_name='importsettings',
            name='service_url',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Адрес SOAP-сервиса'),
        ),
        migrations.AlterField(
            model_name='importsettings',
            name='source_type',
            field=models.CharField(choices=[('local_json', 'Локальный JSON'), ('soap', 'SOAP-сервис')], default='soap', max_length=20, verbose_name='Источник данных'),
        ),
    ]
